export const motivationalQuotes: string[] = [
    "Believe you can and you're halfway there.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Success is not for the lazy.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Stay positive, work hard, make it happen.",
    "Success is what happens after you have survived all your mistakes.",
    "Don’t limit your challenges. Challenge your limits.",
    "The key to success is to focus on goals, not obstacles.",
    "The harder you work today, the luckier you get tomorrow.",
    "Doubt kills more dreams than failure ever will.",
    "Don’t stop until you’re proud.",
    "If you get tired, learn to rest, not quit.",
    "Difficult roads often lead to beautiful destinations.",
    "Push yourself, because no one else is going to do it for you.",
    "Work hard in silence. Let success be your noise.",
    "Act as if what you do makes a difference. It does.",
    "Stay hungry. Stay foolish.",
    "Opportunities don't happen, you create them.",
    "Don’t wish it were easier. Wish you were better.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Do what you can with all you have, wherever you are.",
    "Fall seven times and stand up eight.",
    "What defines us is how well we rise after falling.",
    "Don’t be afraid to give up the good to go for the great.",
    "I never dreamed about success. I worked for it.",
    "The way to get started is to quit talking and begin doing.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Go the extra mile. It’s never crowded there.",
    "Don’t count the days, make the days count.",
    "Winners never quit, and quitters never win.",
    "The future depends on what you do today.",
    "Difficulties in life don’t come to destroy you, but to help you realize your potential.",
    "Don’t fear failure. Fear being in the exact same place next year as you are today.",
    "Work until your idols become your rivals.",
    "Discipline is the bridge between goals and accomplishment.",
    "Don’t stop until you’re proud of yourself."
  ];